services:
  api:
    build:
      context: node-api
      dockerfile: Dockerfile
    image: ${API_IMAGE:-ghcr.io/rd1-io/tigermeter-api:latest}
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: file:/data/api.sqlite
      JWT_SECRET: ${JWT_SECRET}
      HMAC_KEY: ${HMAC_KEY}
      CORS_ALLOWED_ORIGINS: https://emulator.tigermeter.rd1.io
    volumes:
      - api-data:/data
    networks:
      - web

  emulator:
    build:
      context: web-emulator
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://api.tigermeter.rd1.io/api
        VITE_HMAC_KEY: ${HMAC_KEY}
    image: ${EMULATOR_IMAGE:-ghcr.io/rd1-io/tigermeter-emulator:latest}
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - api
      - emulator
    networks:
      - web

volumes:
  api-data:
  caddy-data:
  caddy-config:

networks:
  web:
    driver: bridge






