#!/usr/bin/env python3
"""Generate 64x64 1-bit bitmap C arrays for currency symbols."""

from PIL import Image, ImageDraw, ImageFont
import sys
import os

SYMBOLS = {
    "dollar":  "$",
    "euro":    "€",
    "pound":   "£",
    "yuan":    "¥",
    "ruble":   "₽",
    "bitcoin": "₿",
    "eth":     "Ξ",
}

SIZE = 64
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "..", "firmware", "src", "CurrencySymbols.h")

def test_font_has_glyph(font_path, char, size=52):
    """Test if a font actually renders a character (not just a .notdef box)."""
    try:
        font = ImageFont.truetype(font_path, size)
        img = Image.new('L', (80, 80), 255)
        d = ImageDraw.Draw(img)
        d.text((5, 5), char, font=font, fill=0)
        pixels = list(img.getdata())
        dark = sum(1 for p in pixels if p < 128)
        return dark > 200  # Real glyph has many dark pixels
    except Exception:
        return False

def find_font_for_char(char):
    """Find the best bold font that actually renders this character."""
    # Prefer bold fonts first, then regular
    candidates = [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/SFNSRounded.ttf",
        "/System/Library/Fonts/HelveticaNeue.ttc",
        "/System/Library/Fonts/Helvetica.ttc",
        "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
        "/System/Library/Fonts/Supplemental/Verdana Bold.ttf",
    ]
    for path in candidates:
        if os.path.exists(path) and test_font_has_glyph(path, char):
            return path
    # Last resort
    return candidates[0]

def render_symbol(char, font_path=None, size=SIZE):
    """Render a character to a 1-bit bitmap (1=white, 0=black)."""
    if font_path is None:
        font_path = find_font_for_char(char)
    img = Image.new('1', (size, size), 1)  # White background
    draw = ImageDraw.Draw(img)
    
    # Try larger font sizes for bolder appearance
    for fs in [60, 56, 52, 48, 44]:
        font = ImageFont.truetype(font_path, fs)
        bbox = draw.textbbox((0, 0), char, font=font)
        tw = bbox[2] - bbox[0]
        th = bbox[3] - bbox[1]
        if tw <= size - 2 and th <= size - 2:
            break
    
    # Center the character
    x = (size - tw) // 2 - bbox[0]
    y = (size - th) // 2 - bbox[1]
    
    img2 = Image.new('1', (size, size), 1)
    draw2 = ImageDraw.Draw(img2)
    # Draw with stroke for extra boldness
    draw2.text((x, y), char, font=font, fill=0, stroke_width=1, stroke_fill=0)
    
    return img2

def image_to_c_array(img):
    """Convert 1-bit PIL image to C byte array string."""
    pixels = list(img.getdata())
    w = img.width
    h = img.height
    
    bytes_list = []
    for row in range(h):
        for col_byte in range(w // 8):
            byte_val = 0
            for bit in range(8):
                px = pixels[row * w + col_byte * 8 + bit]
                if px:  # White pixel = 1
                    byte_val |= (1 << (7 - bit))
            bytes_list.append(byte_val)
    
    return bytes_list

def main():
    header = """// Auto-generated currency symbol bitmaps for e-paper display
// Size: 64x64 pixels each
// Generated by scripts/gen_symbol_bitmaps.py

#ifndef _CURRENCY_SYMBOLS_H_
#define _CURRENCY_SYMBOLS_H_

#define SYMBOL_BITMAP_WIDTH  64
#define SYMBOL_BITMAP_HEIGHT 64

"""
    
    for name, char in SYMBOLS.items():
        fp = find_font_for_char(char)
        print(f"Rendering {name} ({char}) with {os.path.basename(fp)}")
        img = render_symbol(char, fp)
        
        # Save preview PNG
        preview_dir = os.path.join(os.path.dirname(__file__), "..", "firmware", "symbol_previews")
        os.makedirs(preview_dir, exist_ok=True)
        img.save(os.path.join(preview_dir, f"{name}.png"))
        
        bytes_data = image_to_c_array(img)
        
        var_name = f"Symbol_{name}"
        header += f"const unsigned char {var_name}[{len(bytes_data)}] = {{\n"
        
        for i in range(0, len(bytes_data), 16):
            chunk = bytes_data[i:i+16]
            line = ", ".join(f"0x{b:02X}" for b in chunk)
            header += f"    {line},\n"
        
        header += f"}};\n\n"
    
    header += "#endif // _CURRENCY_SYMBOLS_H_\n"
    
    with open(OUTPUT_FILE, 'w') as f:
        f.write(header)
    
    print(f"\nGenerated: {OUTPUT_FILE}")
    print(f"Symbols: {', '.join(SYMBOLS.keys())}")

if __name__ == "__main__":
    main()
